version: "3.9"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: integration-tests-prisma
    expose:
      - 3307
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
